'use client'

import { useState } from 'react'
import { paiaManualSchema, type PaiaManualInput } from '@/lib/validators/paia'
import { useRouter } from 'next/navigation'
import { savePaiaManual } from '@/app/actions/paia'

interface Organization {
  id: string
  name: string
  public_slug: string
}

interface PaiaManualGeneratorProps {
  org: Organization
}

export default function PaiaManualGenerator({ org }: PaiaManualGeneratorProps) {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [generatedMarkdown, setGeneratedMarkdown] = useState<string | null>(null)
  
  const [formData, setFormData] = useState<PaiaManualInput>({
    businessName: org.name,
    registrationNumber: '',
    industry: '',
    informationOfficerName: '',
    informationOfficerEmail: '',
    informationOfficerPhone: '',
    businessAddress: '',
    recordCategories: [],
    dataSubjectCategories: [],
    personalInfoCategories: [],
    thirdPartyRecipients: [],
    crossBorderTransfers: '',
    securitySafeguards: '',
    requestProcess: '',
    contactDetails: '',
  })

  const [categoryInputs, setCategoryInputs] = useState({
    record: '',
    dataSubject: '',
    personalInfo: '',
    thirdParty: '',
  })

  const addCategory = (type: 'recordCategories' | 'dataSubjectCategories' | 'personalInfoCategories' | 'thirdPartyRecipients') => {
    const inputKey = type === 'recordCategories' ? 'record' : 
                    type === 'dataSubjectCategories' ? 'dataSubject' : 
                    type === 'personalInfoCategories' ? 'personalInfo' : 'thirdParty'
    
    if (categoryInputs[inputKey as keyof typeof categoryInputs].trim()) {
      setFormData({
        ...formData,
        [type]: [...formData[type], categoryInputs[inputKey as keyof typeof categoryInputs].trim()],
      })
      setCategoryInputs({
        ...categoryInputs,
        [inputKey]: '',
      })
    }
  }

  const removeCategory = (type: keyof PaiaManualInput, index: number) => {
    setFormData({
      ...formData,
      [type]: (formData[type] as string[]).filter((_, i) => i !== index),
    })
  }

  const generateMarkdown = () => {
    const md = `# PAIA Manual

## 1. Business Information

**Business Name:** ${formData.businessName}
${formData.registrationNumber ? `**Registration Number:** ${formData.registrationNumber}` : ''}
${formData.industry ? `**Industry:** ${formData.industry}` : ''}
${formData.businessAddress ? `**Business Address:** ${formData.businessAddress}` : ''}

## 2. Information Officer

**Name:** ${formData.informationOfficerName}
**Email:** ${formData.informationOfficerEmail}
${formData.informationOfficerPhone ? `**Phone:** ${formData.informationOfficerPhone}` : ''}

## 3. Records Held by the Private Body

${formData.recordCategories.length > 0 ? formData.recordCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 4. Categories of Data Subjects

${formData.dataSubjectCategories.length > 0 ? formData.dataSubjectCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 5. Categories of Personal Information

${formData.personalInfoCategories.length > 0 ? formData.personalInfoCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 6. Third Party Recipients

${formData.thirdPartyRecipients.length > 0 ? formData.thirdPartyRecipients.map(cat => `- ${cat}`).join('\n') : 'No third parties specified'}

${formData.crossBorderTransfers ? `## 7. Cross-Border Transfers\n\n${formData.crossBorderTransfers}` : ''}

${formData.securitySafeguards ? `## 8. Security Safeguards\n\n${formData.securitySafeguards}` : ''}

${formData.requestProcess ? `## 9. Request Process\n\n${formData.requestProcess}` : ''}

${formData.contactDetails ? `## 10. Contact Details\n\n${formData.contactDetails}` : ''}

---
*Generated by PopiaGo*
`
    return md
  }

  const handlePreview = () => {
    try {
      paiaManualSchema.parse(formData)
      setGeneratedMarkdown(generateMarkdown())
      setError(null)
    } catch {
      setError('Please check your input and ensure all required fields are filled')
    }
  }

  const handleSave = async () => {
    setLoading(true)
    setError(null)

    try {
      const markdown = generateMarkdown()
      const result = await savePaiaManual(formData, markdown)

      if (!result.success) {
        setError(result.error || 'Failed to save manual')
        setLoading(false)
        return
      }

      router.push('/dashboard')
      router.refresh()
    } catch (err) {
      console.error('PAIA save error:', err)
      setError('An unexpected error occurred while saving')
      setLoading(false)
    }
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">PAIA Manual Details</h2>

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        <div className="space-y-4">
          <div>
            <label htmlFor="businessName" className="block text-sm font-medium text-slate-700 mb-1">
              Business Name *
            </label>
            <input
              id="businessName"
              type="text"
              value={formData.businessName}
              onChange={(e) => setFormData({ ...formData, businessName: e.target.value })}
              required
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label htmlFor="registrationNumber" className="block text-sm font-medium text-slate-700 mb-1">
                Registration Number
              </label>
              <input
                id="registrationNumber"
                type="text"
                value={formData.registrationNumber}
                onChange={(e) => setFormData({ ...formData, registrationNumber: e.target.value })}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
            <div>
              <label htmlFor="industry" className="block text-sm font-medium text-slate-700 mb-1">
                Industry
              </label>
              <input
                id="industry"
                type="text"
                value={formData.industry}
                onChange={(e) => setFormData({ ...formData, industry: e.target.value })}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>

          <div>
            <label htmlFor="businessAddress" className="block text-sm font-medium text-slate-700 mb-1">
              Business Address
            </label>
            <textarea
              id="businessAddress"
              value={formData.businessAddress}
              onChange={(e) => setFormData({ ...formData, businessAddress: e.target.value })}
              rows={2}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-slate-900 mb-3">Information Officer</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label htmlFor="ioName" className="block text-sm font-medium text-slate-700 mb-1">
                  Name *
                </label>
                <input
                  id="ioName"
                  type="text"
                  value={formData.informationOfficerName}
                  onChange={(e) => setFormData({ ...formData, informationOfficerName: e.target.value })}
                  required
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
              <div>
                <label htmlFor="ioEmail" className="block text-sm font-medium text-slate-700 mb-1">
                  Email *
                </label>
                <input
                  id="ioEmail"
                  type="email"
                  value={formData.informationOfficerEmail}
                  onChange={(e) => setFormData({ ...formData, informationOfficerEmail: e.target.value })}
                  required
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>
            <div className="mt-3">
              <label htmlFor="ioPhone" className="block text-sm font-medium text-slate-700 mb-1">
                Phone
              </label>
              <input
                id="ioPhone"
                type="text"
                value={formData.informationOfficerPhone}
                onChange={(e) => setFormData({ ...formData, informationOfficerPhone: e.target.value })}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-slate-900 mb-3">Record Categories</h3>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={categoryInputs.record}
                onChange={(e) => setCategoryInputs({ ...categoryInputs, record: e.target.value })}
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addCategory('recordCategories'))}
                className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="e.g., Customer records"
              />
              <button
                type="button"
                onClick={() => addCategory('recordCategories')}
                className="bg-slate-200 text-slate-700 px-4 py-2 rounded-lg hover:bg-slate-300 transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.recordCategories.map((cat, index) => (
                <span key={index} className="inline-flex items-center gap-1 bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm">
                  {cat}
                  <button type="button" onClick={() => removeCategory('recordCategories', index)} className="hover:text-blue-900">×</button>
                </span>
              ))}
            </div>
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-slate-900 mb-3">Data Subject Categories</h3>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={categoryInputs.dataSubject}
                onChange={(e) => setCategoryInputs({ ...categoryInputs, dataSubject: e.target.value })}
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addCategory('dataSubjectCategories'))}
                className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="e.g., Customers"
              />
              <button
                type="button"
                onClick={() => addCategory('dataSubjectCategories')}
                className="bg-slate-200 text-slate-700 px-4 py-2 rounded-lg hover:bg-slate-300 transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.dataSubjectCategories.map((cat, index) => (
                <span key={index} className="inline-flex items-center gap-1 bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-sm">
                  {cat}
                  <button type="button" onClick={() => removeCategory('dataSubjectCategories', index)} className="hover:text-emerald-900">×</button>
                </span>
              ))}
            </div>
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-slate-900 mb-3">Personal Information Categories</h3>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={categoryInputs.personalInfo}
                onChange={(e) => setCategoryInputs({ ...categoryInputs, personalInfo: e.target.value })}
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addCategory('personalInfoCategories'))}
                className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="e.g., Contact details"
              />
              <button
                type="button"
                onClick={() => addCategory('personalInfoCategories')}
                className="bg-slate-200 text-slate-700 px-4 py-2 rounded-lg hover:bg-slate-300 transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.personalInfoCategories.map((cat, index) => (
                <span key={index} className="inline-flex items-center gap-1 bg-purple-100 text-purple-800 px-3 py-1 rounded-full text-sm">
                  {cat}
                  <button type="button" onClick={() => removeCategory('personalInfoCategories', index)} className="hover:text-purple-900">×</button>
                </span>
              ))}
            </div>
          </div>

          <div className="border-t pt-4">
            <h3 className="text-md font-semibold text-slate-900 mb-3">Third Party Recipients</h3>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={categoryInputs.thirdParty}
                onChange={(e) => setCategoryInputs({ ...categoryInputs, thirdParty: e.target.value })}
                onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addCategory('thirdPartyRecipients'))}
                className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="e.g., Cloud provider"
              />
              <button
                type="button"
                onClick={() => addCategory('thirdPartyRecipients')}
                className="bg-slate-200 text-slate-700 px-4 py-2 rounded-lg hover:bg-slate-300 transition-colors"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.thirdPartyRecipients.map((cat, index) => (
                <span key={index} className="inline-flex items-center gap-1 bg-amber-100 text-amber-800 px-3 py-1 rounded-full text-sm">
                  {cat}
                  <button type="button" onClick={() => removeCategory('thirdPartyRecipients', index)} className="hover:text-amber-900">×</button>
                </span>
              ))}
            </div>
          </div>

          <div>
            <label htmlFor="crossBorder" className="block text-sm font-medium text-slate-700 mb-1">
              Cross-Border Transfers
            </label>
            <textarea
              id="crossBorder"
              value={formData.crossBorderTransfers}
              onChange={(e) => setFormData({ ...formData, crossBorderTransfers: e.target.value })}
              rows={2}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Describe any cross-border data transfers"
            />
          </div>

          <div>
            <label htmlFor="security" className="block text-sm font-medium text-slate-700 mb-1">
              Security Safeguards
            </label>
            <textarea
              id="security"
              value={formData.securitySafeguards}
              onChange={(e) => setFormData({ ...formData, securitySafeguards: e.target.value })}
              rows={3}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Describe security measures in place"
            />
          </div>

          <div>
            <label htmlFor="requestProcess" className="block text-sm font-medium text-slate-700 mb-1">
              Request Process
            </label>
            <textarea
              id="requestProcess"
              value={formData.requestProcess}
              onChange={(e) => setFormData({ ...formData, requestProcess: e.target.value })}
              rows={3}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Describe how to submit PAIA requests"
            />
          </div>

          <div>
            <label htmlFor="contact" className="block text-sm font-medium text-slate-700 mb-1">
              Contact Details
            </label>
            <textarea
              id="contact"
              value={formData.contactDetails}
              onChange={(e) => setFormData({ ...formData, contactDetails: e.target.value })}
              rows={2}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Additional contact information"
            />
          </div>

          <div className="flex gap-4 pt-4">
            <button
              type="button"
              onClick={handlePreview}
              className="flex-1 bg-slate-600 text-white py-2 px-4 rounded-lg hover:bg-slate-700 transition-colors"
            >
              Preview
            </button>
            <button
              type="button"
              onClick={handleSave}
              disabled={loading}
              className="flex-1 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {loading ? 'Saving...' : 'Save Manual'}
            </button>
          </div>
        </div>
      </div>

      {generatedMarkdown && (
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-slate-900 mb-4">Preview</h2>
          <div className="bg-slate-50 rounded-lg p-4 overflow-auto max-h-[600px]">
            <pre className="whitespace-pre-wrap text-sm text-slate-700">{generatedMarkdown}</pre>
          </div>
        </div>
      )}
    </div>
  )
}
