import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { paiaManualSchema } from '@/lib/validators/paia'
import { logAuditEvent } from '@/lib/supabase/audit'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const validatedData = paiaManualSchema.parse(body)

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user's organization
    const { data: orgMember, error: orgMemberError } = await supabase
      .from('org_members')
      .select('org_id')
      .eq('user_id', user.id)
      .maybeSingle()

    if (orgMemberError) {
      console.error('PAIA org lookup error:', orgMemberError)
      return NextResponse.json(
        { error: 'Unable to resolve your organization.' },
        { status: 500 }
      )
    }

    if (!orgMember) {
      return NextResponse.json({ error: 'Organization not found' }, { status: 404 })
    }

    // Generate markdown
    const markdown = `# PAIA Manual

## 1. Business Information

**Business Name:** ${validatedData.businessName}
${validatedData.registrationNumber ? `**Registration Number:** ${validatedData.registrationNumber}` : ''}
${validatedData.industry ? `**Industry:** ${validatedData.industry}` : ''}
${validatedData.businessAddress ? `**Business Address:** ${validatedData.businessAddress}` : ''}

## 2. Information Officer

**Name:** ${validatedData.informationOfficerName}
**Email:** ${validatedData.informationOfficerEmail}
${validatedData.informationOfficerPhone ? `**Phone:** ${validatedData.informationOfficerPhone}` : ''}

## 3. Records Held by the Private Body

${validatedData.recordCategories.length > 0 ? validatedData.recordCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 4. Categories of Data Subjects

${validatedData.dataSubjectCategories.length > 0 ? validatedData.dataSubjectCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 5. Categories of Personal Information

${validatedData.personalInfoCategories.length > 0 ? validatedData.personalInfoCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 6. Third Party Recipients

${validatedData.thirdPartyRecipients.length > 0 ? validatedData.thirdPartyRecipients.map(cat => `- ${cat}`).join('\n') : 'No third parties specified'}

${validatedData.crossBorderTransfers ? `## 7. Cross-Border Transfers\n\n${validatedData.crossBorderTransfers}` : ''}

${validatedData.securitySafeguards ? `## 8. Security Safeguards\n\n${validatedData.securitySafeguards}` : ''}

${validatedData.requestProcess ? `## 9. Request Process\n\n${validatedData.requestProcess}` : ''}

${validatedData.contactDetails ? `## 10. Contact Details\n\n${validatedData.contactDetails}` : ''}

---
*Generated by PopiaGo*
`

    const { data: manual, error: insertError } = await supabase
      .from('paia_manuals')
      .insert({
        org_id: orgMember.org_id,
        business_name: validatedData.businessName,
        registration_number: validatedData.registrationNumber,
        industry: validatedData.industry,
        information_officer_name: validatedData.informationOfficerName,
        information_officer_email: validatedData.informationOfficerEmail,
        information_officer_phone: validatedData.informationOfficerPhone,
        business_address: validatedData.businessAddress,
        record_categories: validatedData.recordCategories,
        data_subject_categories: validatedData.dataSubjectCategories,
        personal_info_categories: validatedData.personalInfoCategories,
        third_party_recipients: validatedData.thirdPartyRecipients,
        cross_border_transfers: validatedData.crossBorderTransfers,
        security_safeguards: validatedData.securitySafeguards,
        request_process: validatedData.requestProcess,
        contact_details: validatedData.contactDetails,
        generated_markdown: markdown,
      })
      .select('id')
      .maybeSingle()

    if (insertError || !manual) {
      console.error('Failed to save PAIA manual:', insertError)
      return NextResponse.json(
        { error: 'Unable to persist PAIA manual at this time.' },
        { status: 500 }
      )
    }

    await logAuditEvent({
      orgId: orgMember.org_id,
      action: 'paia_save',
      entityType: 'paia_manual',
      entityId: manual.id,
      details: { businessName: validatedData.businessName },
    })

    return NextResponse.json({ markdown, id: manual.id })
  } catch (error) {
    console.error('PAIA generation error:', error)
    return NextResponse.json({ error: 'Invalid input' }, { status: 400 })
  }
}
