import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { paiaManualSchema } from '@/lib/validators/paia'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const validatedData = paiaManualSchema.parse(body)

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user's organization
    const { data: orgMember } = await supabase
      .from('org_members')
      .select('org_id')
      .eq('user_id', user.id)
      .single()

    if (!orgMember) {
      return NextResponse.json({ error: 'Organization not found' }, { status: 404 })
    }

    // Generate markdown
    const markdown = `# PAIA Manual

## 1. Business Information

**Business Name:** ${validatedData.businessName}
${validatedData.registrationNumber ? `**Registration Number:** ${validatedData.registrationNumber}` : ''}
${validatedData.industry ? `**Industry:** ${validatedData.industry}` : ''}
${validatedData.businessAddress ? `**Business Address:** ${validatedData.businessAddress}` : ''}

## 2. Information Officer

**Name:** ${validatedData.informationOfficerName}
**Email:** ${validatedData.informationOfficerEmail}
${validatedData.informationOfficerPhone ? `**Phone:** ${validatedData.informationOfficerPhone}` : ''}

## 3. Records Held by the Private Body

${validatedData.recordCategories.length > 0 ? validatedData.recordCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 4. Categories of Data Subjects

${validatedData.dataSubjectCategories.length > 0 ? validatedData.dataSubjectCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 5. Categories of Personal Information

${validatedData.personalInfoCategories.length > 0 ? validatedData.personalInfoCategories.map(cat => `- ${cat}`).join('\n') : 'No categories specified'}

## 6. Third Party Recipients

${validatedData.thirdPartyRecipients.length > 0 ? validatedData.thirdPartyRecipients.map(cat => `- ${cat}`).join('\n') : 'No third parties specified'}

${validatedData.crossBorderTransfers ? `## 7. Cross-Border Transfers\n\n${validatedData.crossBorderTransfers}` : ''}

${validatedData.securitySafeguards ? `## 8. Security Safeguards\n\n${validatedData.securitySafeguards}` : ''}

${validatedData.requestProcess ? `## 9. Request Process\n\n${validatedData.requestProcess}` : ''}

${validatedData.contactDetails ? `## 10. Contact Details\n\n${validatedData.contactDetails}` : ''}

---
*Generated by PopiaGo*
`

    return NextResponse.json({ markdown })
  } catch (error) {
    console.error('PAIA generation error:', error)
    return NextResponse.json({ error: 'Invalid input' }, { status: 400 })
  }
}
